-- Generated by /create-agent for living-room on 2026-04-14
-- Idempotent: safe to re-run.

INSERT INTO agents (
  name, description, lxc_id, lxc_ip, service_name,
  data_table, settings_table,
  deploy_path, git_branch, service_oneshot, enabled
) VALUES (
  'living-room',
  'Living Room Agent that concentrate all operations about this room',
  NULL, NULL, NULL,
  NULL, NULL,
  NULL, NULL, false, true
)
ON CONFLICT (name) DO NOTHING;
