-- Generated by /create-agent for my-bathroom on 2026-05-06
-- Idempotent: safe to re-run.

-- Register in agents table (dashboard-only — no service, no tables).
INSERT INTO agents (
  name, description, lxc_id, lxc_ip, service_name,
  data_table, settings_table,
  deploy_path, git_branch, service_oneshot, enabled
) VALUES (
  'my-bathroom',
  'Per-room agent for My BathRoom — touch panel, smart switch, smell pump, and bathroom-area devices.',
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, true
)
ON CONFLICT (name) DO NOTHING;
