-- Generated by /create-agent for balcony on 2026-05-01
-- Idempotent: safe to re-run.

-- 1) Register in agents table (HASP DB tables already exist with retention; no new tables to create here)
INSERT INTO agents (
  name, description,
  lxc_id, lxc_ip, service_name,
  data_table, settings_table,
  deploy_path, git_branch,
  service_oneshot, enabled
) VALUES (
  'balcony',
  'Per-room agent for the balcony — OpenHASP touch panel, rules, and balcony-area devices (gates, barrier, lights).',
  NULL, NULL, NULL,
  NULL, NULL,
  NULL, NULL,
  false, true
)
ON CONFLICT (name) DO NOTHING;
