-- Generated by /create-agent for bedroom on 2026-06-13
-- Idempotent: safe to re-run.

-- Register Bedroom Agent in the agents table (dashboard-only — no service layer).
INSERT INTO agents (
  name, description, lxc_id, lxc_ip, service_name,
  data_table, settings_table, deploy_path, git_branch, service_oneshot, enabled
) VALUES (
  'bedroom',
  'Per-room agent for the Bedroom — area-specific control surfaces and automations.',
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, true
)
ON CONFLICT (name) DO NOTHING;

-- No data/settings tables yet (config will live in dashboard_settings under
-- the 'bedroom.*' key prefix as features are added). No retention rows needed.
